""" 
Configuration file for GSAT with Tabu and Novelty Plus and TSP
"""

# parameters for processing the GSAT WITH TABU AND NOVELTY
CNF_FILEPATH = '/data/Inst'

TABU_LIST_LENGTH = 5

GSAT_TABU_ITER = 1000
GSAT_TABU_RESTART = 10


GSAT_NOVELTY_ITER = 100000
GSAT_NOVELTY_MAXOUT_TIME_IF_ITER_ARE_MORE = 60
GSAT_NOVELTY_RESTART = 1
GSAT_NOVELTY_WP = 0.4
GSAT_NOVELTY_P = 0.3


# parameters for processing the TSP
TSP_FILEPATH = '/data/Tsp'

TSP_DIRECT_SELECTION = 5
TSP_EXECUTION_PER_MINUTE = 300
TSP_LEAST_NUMBER_OF_EXECUTION = 5
